Serveur DNS#DNS
Service WINS (Windows Internet Name Service)#Wins
VNC Server Version 4#VNC
Spouleur dimpression#Spool
Symantec AntiVirus Definition Watcher#NAV upd
Symantec AntiVirus#NAV
Symantec System Center Discovery Service#SSC
Service de rep rage Symantec System Center#SSC
Service de d tection de Symantec System Center#SSC
CACTID#Cactid
Kiwi Syslog Daemon#Syslog
shiva access manager v5#Shiva
update services#WSUS
simple mail transfer protocol (smtp)#SMTP
service pop3 microsoft#POP
apache2#Apache